services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  web:
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8000/health/web
      interval: 2s
      retries: 10

